import { ClientBottomNav } from "@/components/ClientBottomNav";
import { Button } from "@/components/ui/button";
import { Building2, Globe2, Search } from "lucide-react";

const logoUrl = "/manus-storage/alwaleed-philanthropies-mark_d87d264e.jpg";

export default function ClientExperiencePreview() {
  return <main className="min-h-dvh bg-[#e8efe9] p-0 sm:p-6" dir="rtl"><section className="relative mx-auto flex min-h-dvh max-w-md flex-col overflow-hidden bg-white pb-24 shadow-2xl sm:min-h-[760px] sm:rounded-[2rem]"><div className="pointer-events-none absolute -right-24 top-30 size-72 opacity-[.05]"><img src={logoUrl} alt="" className="size-full object-contain" /></div><header className="relative z-10 flex items-center justify-between bg-[#075e54] px-4 py-3 text-white shadow-lg"><div className="flex items-center gap-3"><img src={logoUrl} alt="مؤسسة الوليد بن طلال الإنسانية" className="size-10 rounded-xl bg-white/10 object-contain p-1" /><div><h1 className="text-sm font-bold">مؤسسة الوليد للإنسانية</h1><p className="mt-0.5 text-[11px] text-emerald-100">الموقع الرسمي داخل مراسلة المؤسسة</p></div></div><Button type="button" variant="ghost" size="icon" className="size-9 text-white hover:bg-white/15 hover:text-white" aria-label="بحث"><Search className="size-4" /></Button></header><div className="relative z-10 flex-1 p-5"><section className="rounded-3xl bg-gradient-to-br from-[#075e54] to-[#128c7e] p-5 text-white shadow-xl shadow-emerald-950/10"><Building2 className="size-8 text-emerald-100" /><h2 className="mt-5 text-xl font-extrabold leading-8">ابدأ من محتوى المؤسسة</h2><p className="mt-3 text-sm leading-7 text-emerald-50">يفتح رابط العميل الموقع الرسمي مباشرةً، وتبقى أدوات الدعم والملف والقبول في متناولك دائماً.</p><Button type="button" className="mt-5 rounded-xl bg-white text-[#075e54] hover:bg-emerald-50"><Globe2 className="ml-2 size-4" />الموقع الرسمي</Button></section><section className="mt-5 rounded-2xl border border-slate-100 bg-white p-4"><p className="text-xs font-bold text-slate-500">تجربة العميل</p><p className="mt-2 text-sm leading-7 text-slate-700">علامة مائية هادئة، وتدرج مؤسسي، وشريط تنقّل ثابت مرفوع عن أسفل الشاشة لتسهيل الوصول بيد واحدة.</p></section></div><ClientBottomNav publicId="preview" active="institution" /></section></main>;
}
