import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Bell, ChevronLeft, MessageCircle, Phone, Settings, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const logoUrl = "/manus-storage/alwaleed-philanthropies-mark_d87d264e.jpg";

export default function ClientDemo() {
  const [, setLocation] = useLocation();
  const phone = sessionStorage.getItem("institution-demo-phone") ?? "";
  return <main className="min-h-screen bg-[#e8efe9] p-0 sm:p-6" dir="rtl"><section className="mx-auto flex min-h-screen max-w-md flex-col overflow-hidden bg-white shadow-2xl sm:min-h-[760px] sm:rounded-[2rem]"><header className="bg-[#075e54] px-4 pb-5 pt-4 text-white"><div className="flex items-center justify-between"><h1 className="text-lg font-bold">مراسلة المؤسسة</h1><div className="flex gap-1"><Button variant="ghost" size="icon" className="size-9 text-white hover:bg-white/15 hover:text-white" onClick={() => toast.message("لا توجد إشعارات جديدة في العرض التجريبي.")}><Bell className="size-5" /></Button><Button variant="ghost" size="icon" className="size-9 text-white hover:bg-white/15 hover:text-white" onClick={() => toast.message(`رقم الهاتف التجريبي: ${phone || "غير مسجل"}`)}><Settings className="size-5" /></Button></div></div><p className="mt-1 text-xs text-emerald-100">مؤسسة الوليد بن طلال الإنسانية</p></header><div className="bg-amber-50 px-4 py-2 text-center text-[11px] font-semibold text-amber-800">عرض تجريبي للواجهة — لا يتم إرسال رمز SMS أو فتح محادثة حقيقية.</div><div className="flex-1 bg-white"><button onClick={() => setLocation("/client-demo/chat")} className="flex w-full items-center gap-3 border-b border-slate-100 px-4 py-4 text-right transition hover:bg-emerald-50/40"><Avatar className="size-14 border border-emerald-100"><AvatarImage src={logoUrl} alt="مؤسسة الوليد بن طلال الإنسانية" /><AvatarFallback>م</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate font-bold text-slate-900">مراسلة المؤسسة</p><span className="text-[11px] text-slate-400">الآن</span></div><p className="mt-1 line-clamp-1 text-xs leading-5 text-slate-500">مرحباً بك، كيف يمكننا مساعدتك؟</p></div><ChevronLeft className="size-5 text-slate-300" /></button></div><nav className="grid grid-cols-3 border-t border-slate-100 bg-white py-2"><button className="flex flex-col items-center gap-1 text-[11px] font-bold text-[#128c7e]"><MessageCircle className="size-5" />المحادثات</button><button onClick={() => toast.message("المكالمات الحية تتطلب تسجيل دخول هاتفياً حقيقياً.")} className="flex flex-col items-center gap-1 text-[11px] text-slate-500"><Phone className="size-5" />المكالمات</button><button onClick={() => toast.message("يُستبدل العرض التجريبي بإعدادات الحساب بعد ربط SMS.")} className="flex flex-col items-center gap-1 text-[11px] text-slate-500"><ShieldCheck className="size-5" />الخصوصية</button></nav></section></main>;
}
