import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Bot, CheckCircle2, Download, Loader2, Mic2, Play, Plus, Power, Radio, RefreshCw, Trash2, Volume2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export function VoiceStatus() {
  const status = trpc.voice.status.useQuery(undefined, { refetchInterval: 10_000 });
  const providerHealth = trpc.voice.providerHealth.useQuery(undefined, { refetchInterval: 60_000, retry: false });
  const configured = Boolean(status.data?.configured);
  return <main className="mx-auto max-w-5xl" dir="rtl"><header className="rounded-3xl bg-gradient-to-l from-blue-700 via-blue-600 to-blue-500 px-6 py-7 text-white shadow-xl shadow-blue-200"><p className="text-xs font-bold tracking-[.16em] text-blue-100">VOICE AI</p><h1 className="mt-2 text-2xl font-bold">الصوت والتحويل الحي</h1><p className="mt-1 text-sm text-blue-100">اختيار صوت حقيقي من مكتبتك وتطبيقه على الصوت المُرسل للعميل.</p></header><section className="mt-5 grid gap-4 sm:grid-cols-3"><article className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><Bot className="size-6 text-blue-600" /><p className="mt-4 text-sm text-slate-500">المزوّد</p><p className="mt-1 text-xl font-bold text-slate-900">{status.data?.provider ?? "جارٍ التحقق"}</p></article><article className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><Mic2 className="size-6 text-blue-600" /><p className="mt-4 text-sm text-slate-500">الأصوات المستوردة</p><p className="mt-1 text-xl font-bold text-slate-900">{status.data?.models ?? 0}</p></article><article className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><Radio className="size-6 text-blue-600" /><p className="mt-4 text-sm text-slate-500">سعة ElevenLabs</p><p className={`mt-1 text-xl font-bold ${providerHealth.data?.connected ? "text-emerald-700" : "text-amber-700"}`}>{providerHealth.isLoading ? "جارٍ التحقق" : providerHealth.data?.capacity ?? "غير معروفة"}</p><p className="mt-1 text-xs text-slate-500">{providerHealth.data?.connected ? `الخطة: ${providerHealth.data.tier}` : "لا تظهر أي مفاتيح أو أرصدة رقمية"}</p></article></section><p className={`mt-5 rounded-2xl border p-4 text-sm leading-7 ${configured ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-amber-200 bg-amber-50 text-amber-800"}`}>{configured ? <>تم التحقق من تكامل <strong>ElevenLabs</strong>. انتقل إلى «النماذج الصوتية» لاستيراد صوت واختياره للمكالمات.</> : <>الحالة: <strong>NOT CONFIGURED</strong>. أضف مفتاح ElevenLabs سرياً من إعدادات المشروع لتفعيل مكتبة الأصوات.</>}</p>{providerHealth.data?.connected && <p className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-7 text-amber-900">تتحقق هذه البطاقة من حالة الاشتراك فقط، ولا تختبر التوليد أو التحويل كي لا تستهلك رصيداً. تستمر المكالمات بالصوت الطبيعي تلقائياً عند رفض المزود لأي طلب.</p>}</main>;
}

export function VoiceModels() {
  const utils = trpc.useUtils();
  const [name, setName] = useState("");
  const [voiceId, setVoiceId] = useState("");
  const list = trpc.voice.listModels.useQuery();
  const catalog = trpc.voice.catalog.useQuery(undefined, { retry: false });
  const active = trpc.voice.activeModel.useQuery();
  const create = trpc.voice.createModel.useMutation({ onSuccess: () => { setName(""); setVoiceId(""); utils.voice.listModels.invalidate(); toast.success("تم حفظ الصوت في مكتبتك."); }, onError: error => toast.error(error.message) });
  const importVoice = trpc.voice.importElevenLabsVoice.useMutation({ onSuccess: () => { utils.voice.listModels.invalidate(); utils.voice.status.invalidate(); toast.success("تم استيراد الصوت من ElevenLabs."); }, onError: error => toast.error(error.message) });
  const update = trpc.voice.updateModel.useMutation({ onSuccess: () => { utils.voice.listModels.invalidate(); utils.voice.activeModel.invalidate(); } });
  const remove = trpc.voice.removeModel.useMutation({ onSuccess: () => { utils.voice.listModels.invalidate(); utils.voice.activeModel.invalidate(); toast.success("تم حذف الصوت من مكتبتك."); } });
  const setActive = trpc.voice.setActiveModel.useMutation({ onSuccess: () => { utils.voice.activeModel.invalidate(); toast.success("سيُطبق الصوت المختار على صوت فريق الدعم المُرسل للعميل."); }, onError: error => toast.error(error.message) });
  const preview = trpc.voice.preview.useMutation({ onSuccess: result => { const audio = new Audio(`data:${result.mimeType};base64,${result.audioBase64}`); void audio.play().catch(() => toast.error("تطلب المعاينة تفاعلاً من المتصفح.")); }, onError: error => toast.error(error.message) });
  const importedIds = new Set(list.data?.filter(model => model.provider === "ElevenLabs").map(model => model.voiceId));

  return <main className="mx-auto max-w-6xl" dir="rtl"><header className="rounded-3xl bg-gradient-to-l from-blue-700 via-blue-600 to-blue-500 px-6 py-7 text-white shadow-xl shadow-blue-200"><p className="text-xs font-bold tracking-[.16em] text-blue-100">VOICE LIBRARY</p><h1 className="mt-2 text-2xl font-bold">مكتبة الأصوات</h1><p className="mt-1 text-sm text-blue-100">استورد صوتاً من ElevenLabs، استمع إلى معاينته، ثم اختره لصوت فريق الدعم في المكالمة.</p></header>

    <section className="mt-5 rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Radio className="size-4" /></span><h2 className="font-bold text-slate-900">الصوت النشط للمكالمات</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">هذا الصوت يغيّر الصوت الذي يسمعه العميل من فريق الدعم، بينما يبقى صوت العميل الأصلي مسموعاً للفريق.</p></div><div className="w-full sm:max-w-sm"><Select value={active.data ? String(active.data.id) : "none"} onValueChange={value => setActive.mutate({ modelId: value === "none" ? null : Number(value) })}><SelectTrigger className="h-11 rounded-xl"><SelectValue placeholder="اختر صوتاً" /></SelectTrigger><SelectContent dir="rtl"><SelectItem value="none">استخدم الصوت الطبيعي</SelectItem>{list.data?.filter(model => model.status === "active").map(model => <SelectItem key={model.id} value={String(model.id)}>{model.name} · {model.provider}</SelectItem>)}</SelectContent></Select></div></div>{active.data && <div className="mt-4 flex items-center gap-2 rounded-2xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><CheckCircle2 className="size-4" />الصوت النشط حالياً: <strong>{active.data.name}</strong></div>}</section>

    <section className="mt-5 rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Volume2 className="size-4" /></span><h2 className="font-bold text-slate-900">أصوات ElevenLabs المتاحة</h2></div><p className="mt-2 text-sm text-slate-500">تُعرض فقط أصوات حساب ElevenLabs المرتبط بالمفتاح السري.</p></div><Button variant="outline" onClick={() => catalog.refetch()} disabled={catalog.isFetching} className="rounded-xl"><RefreshCw className={`ml-2 size-4 ${catalog.isFetching ? "animate-spin" : ""}`} />تحديث المكتبة</Button></div>{catalog.isLoading ? <div className="flex justify-center p-10"><Loader2 className="size-5 animate-spin text-blue-600" /></div> : catalog.isError ? <p className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-red-700">تعذر استرجاع مكتبة الأصوات. تحقق من مفتاح ElevenLabs أو صلاحية الحساب.</p> : <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{catalog.data?.map(voice => <article key={voice.voiceId} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-800">{voice.name}</p><p className="mt-1 text-xs text-slate-400">{voice.category ?? "صوت محفوظ"}{voice.labels.gender ? ` · ${voice.labels.gender}` : ""}</p></div>{importedIds.has(voice.voiceId) ? <Badge className="border-0 bg-emerald-50 text-emerald-700">مستورَد</Badge> : null}</div><p className="mt-3 min-h-10 text-xs leading-5 text-slate-500">{voice.description ?? "صوت متاح في حساب ElevenLabs."}</p><div className="mt-4 flex gap-2"><Button variant="outline" size="sm" onClick={() => { const model = list.data?.find(item => item.voiceId === voice.voiceId); if (model) preview.mutate({ modelId: model.id }); else toast.message("استورد الصوت أولاً لتشغيل المعاينة الآمنة."); }} disabled={preview.isPending} className="rounded-xl"><Play className="ml-1 size-3.5" />معاينة</Button><Button size="sm" onClick={() => importVoice.mutate({ voiceId: voice.voiceId })} disabled={importedIds.has(voice.voiceId) || importVoice.isPending} className="rounded-xl bg-blue-600 hover:bg-blue-700"><Download className="ml-1 size-3.5" />استيراد</Button></div></article>)}{catalog.data?.length === 0 && <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">لا توجد أصوات محفوظة في حساب ElevenLabs. أضف صوتاً إلى مكتبتك في ElevenLabs ثم حدّث هذه الصفحة.</p>}</div>}</section>

    <section className="mt-5 rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Plus className="size-4 text-blue-600" /><h2 className="font-bold text-slate-900">إضافة صوت بمعرّف Voice ID</h2></div><div className="grid gap-3 lg:grid-cols-3"><Input value={name} onChange={event => setName(event.target.value)} placeholder="اسم الصوت" className="h-11 rounded-xl text-right" /><Input value={voiceId} onChange={event => setVoiceId(event.target.value)} placeholder="Voice ID من ElevenLabs" className="h-11 rounded-xl text-right" /><Button disabled={!name || !voiceId || create.isPending} onClick={() => create.mutate({ name, provider: "ElevenLabs", voiceId })} className="h-11 rounded-xl bg-blue-600 hover:bg-blue-700"><Plus className="ml-2 size-4" />إضافة إلى مكتبتي</Button></div></section>

    <section className="mt-5 overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm">{list.isLoading && <div className="flex justify-center p-12"><Loader2 className="size-5 animate-spin text-blue-600" /></div>}{!list.isLoading && !list.data?.length && <p className="p-10 text-center text-sm text-slate-400">استورد صوتاً من المكتبة أو أضف Voice ID لبدء الاستخدام.</p>}{list.data?.map(model => <article key={model.id} className="flex flex-col gap-3 border-b border-blue-50 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-800">{model.name}</p><p className="mt-1 text-xs text-slate-400">{model.provider} · {model.voiceId}</p></div><div className="flex flex-wrap items-center gap-2"><Badge className={`border-0 ${model.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{model.status === "active" ? "نشط" : "معطل"}</Badge><Button variant="outline" size="sm" onClick={() => preview.mutate({ modelId: model.id })} disabled={model.status !== "active" || preview.isPending} className="rounded-xl"><Play className="ml-1 size-3.5" />معاينة</Button><Button variant="outline" size="icon" onClick={() => update.mutate({ id: model.id, status: model.status === "active" ? "disabled" : "active" })} className="rounded-xl"><Power className="size-4" /><span className="sr-only">تبديل الحالة</span></Button><Button variant="outline" size="icon" onClick={() => remove.mutate({ id: model.id })} className="rounded-xl border-red-200 text-red-600"><Trash2 className="size-4" /><span className="sr-only">حذف</span></Button></div></article>)}</section>
  </main>;
}
