import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Loader2, Mic, MicOff, PhoneCall, PhoneOff } from "lucide-react";
import { Socket, io } from "socket.io-client";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

type OwnerCallStage = "idle" | "calling" | "ringing" | "connecting" | "connected" | "reconnecting" | "failed" | "missed";

export function OwnerOutgoingCall({ conversationId, disabled = false }: { conversationId: number; disabled?: boolean }) {
  const [callId, setCallId] = useState<number | null>(null); const [stage, setStage] = useState<OwnerCallStage>("idle"); const [muted, setMuted] = useState(false); const [durationSeconds, setDurationSeconds] = useState(0); const [networkStatus, setNetworkStatus] = useState("في انتظار الاتصال");
  const socketRef = useRef<Socket | null>(null); const peerRef = useRef<RTCPeerConnection | null>(null); const streamRef = useRef<MediaStream | null>(null); const audioRef = useRef<HTMLAudioElement>(null);
  const createCall = trpc.calls.createOwnerDirect.useMutation(); const tokenMutation = trpc.calls.ownerRealtimeToken.useMutation(); const iceQuery = trpc.calls.ownerIceConfig.useQuery();
  const cleanup = () => { peerRef.current?.close(); peerRef.current = null; streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; socketRef.current?.disconnect(); socketRef.current = null; setMuted(false); setDurationSeconds(0); setNetworkStatus("في انتظار الاتصال"); setCallId(null); };
  useEffect(() => () => cleanup(), []);
  useEffect(() => { if (stage !== "connected") return; const started = Date.now() - durationSeconds * 1000; const timer = window.setInterval(() => setDurationSeconds(Math.floor((Date.now() - started) / 1000)), 1000); return () => window.clearInterval(timer); }, [stage]);
  const offer = async (socket: Socket, activeCallId: number) => { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream; const peer = new RTCPeerConnection({ iceServers: iceQuery.data?.iceServers as RTCIceServer[] | undefined }); peerRef.current = peer; stream.getTracks().forEach(track => peer.addTrack(track, stream)); peer.onicecandidate = event => { if (event.candidate) socket.emit("webrtc:ice", { callId: activeCallId, candidate: event.candidate.toJSON() }); }; peer.onconnectionstatechange = () => { if (peer.connectionState === "connected") { setStage("connected"); setNetworkStatus("متصل"); } if (peer.connectionState === "disconnected") { setStage("reconnecting"); setNetworkStatus("جارٍ إعادة الاتصال"); } if (peer.connectionState === "failed") { setStage("failed"); setNetworkStatus("فشل الاتصال"); toast.error("فشل اتصال WebRTC. قد يتطلب الاتصال إعداد TURN."); } }; peer.ontrack = event => { if (audioRef.current) audioRef.current.srcObject = event.streams[0]; }; setStage("connecting"); const localOffer = await peer.createOffer(); await peer.setLocalDescription(localOffer); socket.emit("webrtc:offer", { callId: activeCallId, sdp: localOffer }); };
  const start = async () => { try { setStage("calling"); const call = await createCall.mutateAsync({ conversationId }); const auth = await tokenMutation.mutateAsync(); const socket = io({ path: "/api/realtime", transports: ["websocket"], auth: { role: "owner", token: auth.token } }); socketRef.current = socket; setCallId(call.id); socket.on("connect", () => { setStage("ringing"); socket.emit("call:owner-request", { callId: call.id }); }); socket.on("call:accepted", async ({ callId: acceptedId, caller }) => { if (acceptedId !== call.id || caller !== "owner") return; try { await offer(socket, call.id); } catch { setStage("failed"); toast.error("تعذّر الوصول إلى الميكروفون."); socket.emit("call:end", { callId: call.id, reason: "تعذّر الوصول للميكروفون." }); cleanup(); } }); socket.on("webrtc:answer", async ({ callId: answerId, sdp }) => { if (answerId === call.id && peerRef.current) await peerRef.current.setRemoteDescription(sdp); }); socket.on("webrtc:ice", async ({ candidate }) => { if (peerRef.current) await peerRef.current.addIceCandidate(candidate); }); socket.on("call:ended", ({ reason }) => { cleanup(); setStage(typeof reason === "string" && reason.startsWith("مكالمة فائتة") ? "missed" : "idle"); if (reason) toast.message(reason); }); socket.on("connect_error", () => { cleanup(); setStage("failed"); toast.error("تعذّر الوصول إلى خدمة الاتصال الحي."); }); } catch (error) { setStage("failed"); toast.error(error instanceof Error ? error.message : "تعذّر بدء المكالمة."); cleanup(); } };
  const end = () => { if (callId) socketRef.current?.emit("call:end", { callId, reason: "أنهى فريق الدعم المكالمة." }); cleanup(); setStage("idle"); };
  const toggleMute = () => { const next = !muted; streamRef.current?.getAudioTracks().forEach(track => { track.enabled = !next; }); setMuted(next); };
  const label = stage === "calling" ? "جارٍ بدء الاتصال" : stage === "ringing" ? "جارٍ الرنين" : stage === "connecting" ? "جارٍ الاتصال" : stage === "reconnecting" ? "جارٍ إعادة الاتصال" : stage === "connected" ? "متصلة" : stage === "failed" ? "فشلت المكالمة" : "اتصال";
  return <><audio ref={audioRef} autoPlay />{stage === "idle" || stage === "failed" || stage === "missed" ? <div className="flex items-center gap-2">{stage === "missed" && <span className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800">مكالمة فائتة</span>}<Button variant="outline" disabled={disabled || createCall.isPending || tokenMutation.isPending} onClick={start} className="rounded-xl border-blue-200 text-blue-700"><PhoneCall className="ml-2 size-4" />{stage === "failed" || stage === "missed" ? "إعادة المحاولة" : "اتصال"}</Button></div> : <div className="flex items-center gap-2"><span className="text-xs font-semibold text-blue-700">{stage === "connected" ? `${String(Math.floor(durationSeconds / 60)).padStart(2, "0")}:${String(durationSeconds % 60).padStart(2, "0")} · ${networkStatus}` : label}</span>{stage === "connected" && <Button variant="outline" size="icon" onClick={toggleMute} className="size-9 rounded-xl border-blue-200 text-blue-700">{muted ? <MicOff className="size-4" /> : <Mic className="size-4" />}<span className="sr-only">كتم الميكروفون</span></Button>}<Button onClick={end} className="rounded-xl bg-red-600 hover:bg-red-700">{stage === "calling" || stage === "ringing" ? <Loader2 className="ml-2 size-4 animate-spin" /> : <PhoneOff className="ml-2 size-4" />}إنهاء</Button></div>}</>;
}
