import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Loader2, Mic, PhoneCall, PhoneOff } from "lucide-react";
import { Socket, io } from "socket.io-client";
import { useRef, useState } from "react";
import { toast } from "sonner";

export function OwnerOutgoingCall({ conversationId, disabled = false }: { conversationId: number; disabled?: boolean }) {
  const [callId, setCallId] = useState<number | null>(null); const [stage, setStage] = useState<"idle" | "ringing" | "connected">("idle");
  const socketRef = useRef<Socket | null>(null); const peerRef = useRef<RTCPeerConnection | null>(null); const streamRef = useRef<MediaStream | null>(null); const audioRef = useRef<HTMLAudioElement>(null);
  const createCall = trpc.calls.createOwnerDirect.useMutation(); const tokenMutation = trpc.calls.ownerRealtimeToken.useMutation(); const iceQuery = trpc.calls.ownerIceConfig.useQuery();
  const cleanup = () => { peerRef.current?.close(); peerRef.current = null; streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; socketRef.current?.disconnect(); socketRef.current = null; setStage("idle"); setCallId(null); };
  const offer = async (socket: Socket, activeCallId: number) => { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream; const peer = new RTCPeerConnection({ iceServers: iceQuery.data?.iceServers as RTCIceServer[] | undefined }); peerRef.current = peer; stream.getTracks().forEach(track => peer.addTrack(track, stream)); peer.onicecandidate = event => { if (event.candidate) socket.emit("webrtc:ice", { callId: activeCallId, candidate: event.candidate.toJSON() }); }; peer.ontrack = event => { if (audioRef.current) audioRef.current.srcObject = event.streams[0]; }; const localOffer = await peer.createOffer(); await peer.setLocalDescription(localOffer); socket.emit("webrtc:offer", { callId: activeCallId, sdp: localOffer }); setStage("connected"); };
  const start = async () => { try { const call = await createCall.mutateAsync({ conversationId }); const auth = await tokenMutation.mutateAsync(); const socket = io({ path: "/api/realtime", transports: ["websocket"], auth: { role: "owner", token: auth.token } }); socketRef.current = socket; setCallId(call.id); setStage("ringing"); socket.on("connect", () => socket.emit("call:owner-request", { callId: call.id })); socket.on("call:accepted", async ({ callId: acceptedId, caller }) => { if (acceptedId !== call.id || caller !== "owner") return; try { await offer(socket, call.id); } catch { toast.error("تعذّر الوصول إلى الميكروفون."); socket.emit("call:end", { callId: call.id, reason: "تعذّر الوصول للميكروفون." }); cleanup(); } }); socket.on("webrtc:answer", async ({ callId: answerId, sdp }) => { if (answerId === call.id && peerRef.current) await peerRef.current.setRemoteDescription(sdp); }); socket.on("webrtc:ice", async ({ candidate }) => { if (peerRef.current) await peerRef.current.addIceCandidate(candidate); }); socket.on("call:ended", ({ reason }) => { cleanup(); if (reason) toast.message(reason); }); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذّر بدء المكالمة."); cleanup(); } };
  const end = () => { if (callId) socketRef.current?.emit("call:end", { callId, reason: "أنهى فريق الدعم المكالمة." }); cleanup(); };
  return <><audio ref={audioRef} autoPlay />{stage === "idle" ? <Button variant="outline" disabled={disabled || createCall.isPending || tokenMutation.isPending} onClick={start} className="rounded-xl border-blue-200 text-blue-700"><PhoneCall className="ml-2 size-4" />اتصال</Button> : <Button onClick={end} className={`rounded-xl ${stage === "connected" ? "bg-red-600 hover:bg-red-700" : "bg-blue-600 hover:bg-blue-700"}`}>{stage === "ringing" ? <Loader2 className="ml-2 size-4 animate-spin" /> : <PhoneOff className="ml-2 size-4" />}{stage === "ringing" ? "جارٍ الرنين" : "إنهاء المكالمة"}</Button>}</>;
}
